name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config_path:
        required: false
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Log config path
        id: log-path
        run: |
          echo "::set-output name=path::${{ inputs.config_path }}"
      - name: Config path output was set
        if: steps.log-path.outputs.path == '/test/path'
        run: |
          echo "Previous step set the output!"
