name: run-local
on: push
jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      python_versions: ${{ steps.python_versions.outputs.json }}
    steps:
      - name: Set Python versions
        id: python_versions
        run: |
          echo "json=[\"\^3.7\"]" >> $GITHUB_OUTPUT
  python_stuff:
    runs-on: ubuntu-latest
    needs:
      - versions
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.versions.outputs.python_versions) }}
    steps:
      - name: "Check if python version was 3.9"
        if: ${{ matrix.python-version }} == "3.9"
        run: echo "Matrix passed python version 3.9"
